### PR TITLE
Set a default station image

### PR DESCRIPTION
**Pull request by cshields**
Right now station image uploads are mandatory, and if a user does not
have such an image of their setup they will be forced to upload some
random image. Instead, this uses the SatNOGS net logo as a default.
Also fixed the width on said image in add/edit mode.

### CODE REVIEW

**Comment by jinxcat** [comment]
+1

**Comment by jinxcat** [comment]
unless anyone has some other preference for a default image

**Comment by cshields** [comment]
The "SatNOGS-logo-vertical-black" (scaled down) from the presskit might be a better option for default, I didn't want to go adding images just yet.

**Comment by comzeradd** [comment]
Yes the satellite dish from the logo would look much better.

I would also avoid hardcoding an image url in the model. The best approach here is to have this as a setting variable and create a `get_image` method at the Station model.

**Comment by cshields** [comment]
Great idea, will do.  Will also cut down on copies of the default image for each station that way.

**Comment by cshields** [comment]
ugh.  sorry for the messy commit messages.  <-- n00b
Anyway, there is a variable in settings and I added a resized version of the satellite dish to the repo as default.
Also, going this route means an upload only occurs if someone specifies an image.  If not, no upload happens and that is fine as it will default to the static image.

**Comment by comzeradd** [comment]
Nice. It seems to work great. Can you also run a `./manage.py makemigrations` and add the migration to this. It's necessary since we have a change on the model.

Do you know how to squash commits? It would look much better if this was all in one commit.

**Comment by comzeradd** [comment]
Since we are having a code sprint this weekend, I squashed these commits in to one preserving commit authorship. Check out #92

**Comment by cshields** [comment]
Thanks!  And sorry, I was out to a work week and busy around the clock since you asked.  I did try to squash but apparently did it wrong.  Going back to some more git docs for next time.

**Comment by comzeradd** [comment]
Don't worry. [Commit](https://github.com/satnogs/satnogs-network/commit/c67cefd129de26033fc98c97fed30a23e55caa09) merged. Thanks for your first contribution :)

**Pull request closed without merging**
